### ISSUE TITLE
Document HTTP response codes?

### ISSUE THREAD

**Issue by bedge** [fabiomaffioletti/jsondoc#109]
I must be missing something here, but I can't see how to document the possible HTTP response codes using jsondoc. 
I want to include a list of the possible http response values that each method can return, eg:
200, 201, 404, 500, etc.

Where does one put these so they appear on the generated docs page?

**Comment by fabiomaffioletti** [comment]
Currently you can do it with the "responsestatuscode" property of the ApiMethod annotation: see http://jsondoc.org/annotations.html#apimethod. It does not accept a list of response values, because I thought that there is only one "successful" status code. For all the other/error codes there is this annotation: http://jsondoc.org/annotations.html#apierrors.

**Comment by bedge** [comment]
I knew it had to be an RTFM issue, thanks for the info. Great tool BTW.
