### ISSUE TITLE
Can jsondoc  understand spring annotation, like @RequestBody and @PathVariable? 

### ISSUE THREAD

**Issue by volyihin** [fabiomaffioletti/jsondoc#111]
Can jsondoc  understand spring annotation? 
![77fd0631b8bada7177a108b35af8cfb7 1](https://cloud.githubusercontent.com/assets/3828802/7653543/312b15f6-fb1f-11e4-9afe-0c270d05ebfc.png)

If it can, i remove @ApiBodyObject annotation.

**Comment by fabiomaffioletti** [comment]
It does can understand spring's annotations, but it's has an "opt-it" strategy, meaning that you still need to put jsondoc annotations to decide what you would like to document and what not.

**Comment by bedge** [comment]
Would it be possible to have a more global flag to eliminate the need to explicitly add annotations for everything? Maybe a file or package scope flag? 
Would save on a lot of annotation typing.

**Comment by volyihin** [comment]
+1. Yes, it will be convenience. If I mark method as @ApiMethod i mean that this method will be availible in jsondoc with all params. Maybe

**Comment by fabiomaffioletti** [comment]
The good thing about jsondoc is that it is framework agnostic, meaning that you can put its annotation on anything you want (you can even annotate non-controller and non-dto classes and have the doc and playground generated and working properly). To do that I needed to require the "technical writer" to decide what to document, this is the reason behind the "annotate everything" approach. But you are right, @ApiMethod would be enough, in case you are for example annotating a spring controller. Changing that in this moment would mean a lot of work though, which I cannot afford right now.

**Comment by rajiv-shringi-A1** [comment]
+1 for this enhancement. The opt-in approach can be controlled by a package level global flag (example: if the flag is true for a given package, then you have to opt in and explicitly annotate in order to generate documentation for the controllers in that package). But that should be only for annotations @Api and/or @ApiMethod. I believe the @ApiPathParam, @ApiRequestBody annotations are redundant. The @PathVariable and @RequestBody annotations should be enough for generating playground.
