### ISSUE TITLE
API status annotation

### ISSUE THREAD

**Issue by ntatsumi** [fabiomaffioletti/jsondoc#122]
I have a need to indicate the status of API class and API methods that informs the consumers whether they are in "public", "private", "deprecated", or "beta" mode. I'd like to create a PR that introduces 'ApiStatus' annotation with the following signature:

Level: class, method

Property: public, deprecated, beta (all defaults to false)

Let me know what you think! Thanks.

**Comment by fabiomaffioletti** [comment]
I think you are mixing different concepts here: public / private belong to the "visibility" world. beta / deprecated and related stuff like alpha, RC, GA belong to the "development stage". Plus I would not add another annotation because people is already saying that there are too many annotation that make their code dirty.

So here is what I would do.
1) add two properties to the @Api and @ApiMethod annotations, named "visibility" and "stage"
2) visibility is an enum ApiVisilibity with values PRIVATE, PUBLIC. Defaults to empty, meaning that it's not mandatory for the user to fill the property with a value. In case it's empty then it's not shown on the UI.
3) stage is an enum ApiStage with values PRE-ALPHA, ALPHA, BETA, RC, GA, DEPRECATED. Defaults to empty, meaning that it's not mandatory for the user to fill the property with a value. In case it's empty then it's not shown on the UI.
4) methods inherit visibility and stage from types.
5) if both method and type specify the visibility, then the type value will override the method one: if the type is PRIVATE, the method cannot be PUBLIC and vice versa
6) the same goes for the stage

Let me know what you think and if you want to modify your pull request. Thanks.

**Comment by ntatsumi** [comment]
You bring up some good points. I'll create another PR based on the design considerations you listed.

**Comment by ntatsumi** [comment]
@fabiomaffioletti I'd like to add visibility and stage to ApiObject as well. Let me know if I can add it to this PR or I should create a separate issue. Thanks.

**Comment by fabiomaffioletti** [comment]
The task is ok, but I suggest you to wait a bit: I made a bit of refactoring in the ISSUE-127 branch so it's better to wait for me to merge it to master before implementing this. I also had to take your work and manually integrate it in the branch. I'll let you know, is it ok for you?

**Comment by ntatsumi** [comment]
Sure. That works.

**Comment by fabiomaffioletti** [comment]
Just merged branch ISSUE-127 to master. Be sure to start from this before adding visibility and stage to @ApiObject.

**Comment by fabiomaffioletti** [comment]
@ntatsumi any news on this?

**Comment by ntatsumi** [comment]
@fabiomaffioletti I'll work on it tonight.
