### ISSUE TITLE
Demo Application - /cities POST gives 415 (Unsupported Media Type)

### ISSUE THREAD

**Issue by lukasbradley** [fabiomaffioletti/jsondoc#142]
![image](https://cloud.githubusercontent.com/assets/526286/9837517/8ebe617e-5a0f-11e5-8e74-6d03163a0f3f.png)

**Comment by fabiomaffioletti** [comment]
This is in someway expected: Spring's @RequestMapping annotation does not specify any "consumes" property; that's why in the documentation section for "/cities" POST method, there is also a warning saying that "Warnings that may prevent a correct playground functionality: - Missing documentation data: consumes". So at the end is my fault, because I did not specify the "consumes" property for the controller's method. I'll fix it when I'll release the next version of the library. Thank you.

**Comment by gedhi** [comment]
This commit should fix the problem without any modification:

12c9aaab52695cb68aecd349975da7d44641ac76

You can close the issue IMHO
