### ISSUE TITLE
Support Patch request

### ISSUE THREAD

**Issue by benkiefer** [fabiomaffioletti/jsondoc#48]
We are using the documentation for our spring boot app, and would like to be able to document our patch endpoints. As we discussed over on #47, it sounds like you would like more than changes to ApiVerb, particularly some corresponding changes the ui project. Anything else you can think of?

**Comment by toranb** [comment]
Another quick question - we didn't see any test code for the PUT verb - would/should we write a test for PATCH (and PUT as tech debt) ?

**Comment by fabiomaffioletti** [comment]
Go for it guys, it's an excellent improvement. Regarding the ui, the modification should be very simple: just put something like 
```
.PUT {
	padding-top : 5px;
	background-color: #5bc0de;
}
```
at the top of the jsondoc.jsp page and everything should be fine. I'll take car of bringing your modification to the new project I am working on (jsondoc-ui-webjar), which is still experimental.

It would be very good to write a test for the PATCH verb, so I'll be glad if you could add it. Regarding the PUT test code, I would very appreciate if you could add a test as well, otherwise I agree to put it as tech debt. Thank you

**Comment by benkiefer** [comment]
Let me know if there is anything else needed. The css change you mentioned was also needed in the css file in the webjar project. Other than that. I was able to stand up a quick example app with a patch method and verify that everything looks great.

**Comment by benkiefer** [comment]
Also, I tried out the spring boot module, and it works great. Thanks again!

**Comment by fabiomaffioletti** [comment]
Glad to hear that. I'll maybe set up so more documentation on how to use the spring boot module. Your pull request has been merged and I just released version 1.0.9 on Maven Central. It should take a few hours to be available. Thank you very much for this!
