### ISSUE TITLE
Default the jsondoc url?

### ISSUE THREAD

**Issue by jameselsey** [fabiomaffioletti/jsondoc#79]
On the jsondoc ui, can we have the url defaulted via config? Most people would probably have a single set of docs so it seems pointless having to type in the URL each time, it would be a better experience to just open the docs.

Perhaps overload the JSONDocController to take a url

**Comment by fabiomaffioletti** [comment]
If you are using the jsondoc-ui module (not the jsondoc-ui-webjar one) you can already do it. I do that in the jsondoc-sample-springmvc project pom file: https://github.com/fabiomaffioletti/jsondoc-samples/blob/master/jsondoc-sample-springmvc/pom.xml

Basically in the jsondoc.jsp file there is a placehoder called ${jsondoc.path}, which you can specify in your pom file and that will get the jsondoc-jsp page filtered when building the war (provided that you properly use the maven war plugin), or when running jetty:run-war.

By the way, take a look at the pom file for jsondoc-sample-springmvc: the integration and filtering of the jsondoc-ui module is automatic.

**Comment by fabiomaffioletti** [comment]
I am considering this cleared.

**Comment by TomGault** [comment]
For someone who's still learning Maven, the webjar module is easier to use because you have wonderful explicit instructions on your webpage.  I have a couple suggestions that might help:

1) Would it make sense to add a wee bit of JavaScript to the webjar module's index.html to get the jsondoc path from a query parameter?  Then we could solve the problem with links and bookmarks.  Right now refreshing the page even loses the URL.  Related:  Why did you explicitly disallow auto-complete?

2) I love your project!  You sir understand how to make simple, helpful documentation and you've helped us to make the same!  This may be a dumb question, but would it make sense to add instructions for Maven noobs like me for how to get our project to build with the jsondoc-ui module?  Thanks again for this great tool!

**Comment by TomGault** [comment]
NEVERMIND.  You've already done #1!  For anyone following along, just add `?url=<MyJsonDocPath>` to pre-populate the field and load your documentation.

Thanks!
