### ISSUE TITLE
Offline docs / distributable docs?

### ISSUE THREAD

**Issue by jameselsey** [fabiomaffioletti/jsondoc#80]
More of a question than an issue...

Are there any features/workarounds to have offline documentation? For example if developers don't have access to your hosted API docs, is there an easy way to save these, or generate something to distribute?

**Comment by fabiomaffioletti** [comment]
Currently there are two ways of doing that:
1) use the jsondoc-maven-plugin (how to on the website). But the plugin uses the DefaultJSONDocScanner, so if you are in a Spring project it will probably don't produce the doc you expect (maybe in the future it would be good to let the plugin user specify which scanner implementation to use in the plugin)
2) save the output of the jsondoc endpoint to a file and distribute that file, that is actually a json file containing the documentation. To view that, you can customize the jsondoc-ui to take a json file as input instead of fetching it from a url

**Comment by fabiomaffioletti** [comment]
Reopen if needed.
