### ISSUE TITLE
Global documentation data

### ISSUE THREAD

**Issue by fabiomaffioletti** [fabiomaffioletti/jsondoc#99]
Manage documentation that is valid across the whole API, for example:
- in this app, GET means retrieving a list of resources or a single resource
- in this app, every request should have header "x" with value "y"
- ...

**Comment by djpotter77** [comment]
It seems like you can already do some of this with in the API description (albeit in a free-form manner).

However, I would really like to see a version of the ApiHeaders and ApiErrors annotations that could be applied at either the controller class level or even a higher level class associated with an entire API group.  Having to repeat all common headers and errors explicitly for every method is a chore, error prone, and really bloats the controller code.

**Comment by djpotter77** [comment]
Although it wouldn't allow truly global headers and errors, it would be pretty simple to allow the ApiHeaders and ApiErrors annotations at the class level so that you can define a set of default headers or errors that get added to any method-specific ones that are defined.  I think it would just involve changing the annotations to allow ElementType.TYPE and updating the ApiHeaderDoc.build() and ApiErrorDoc.build() methods to merge the the class and method level annotations.

**Comment by fabiomaffioletti** [comment]
@djpotter77 with version 1.1.16 it is possible to add the @ApiHeaders annotation at class level
